name: empty-scaffold
channels:
  - conda-forge
dependencies:
  - python=3.9
  - rdkit
  - numpy=1.26.*
  - pandas=2.2.*
  - scipy=1.11.*
  - scikit-learn=1.4.*
  - xgboost=2.*
  - pyyaml
  - tabulate
  - pytest
  - matplotlib=3.8.*
  - openpyxl
  - jupyterlab
  - notebook
  - ipykernel=6.29.*
  - jupyter_client=8.6.*
  - pyzmq=26.*
  - tornado=6.4.*
  - pip
  - pip:
      - umap-learn